layout_spectrum: 0.8254638
color:
  saturation: 0.8693086
  lightness: 0
  brandStrength: 0.4924115
  brandColors:
    - '#FFFFFF'
    - '#271F02'
    - '#CF9A01'
    - '#FFE96E'
    - '#776542'
  rhythmicContrast: 0.1627319
typography_spectrum: 0.4342327
name: North Fork Soap Company
